# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'maininterface.ui'
#
# Created by: PyQt5 UI code generator 5.7.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1622, 1065)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.query_bar = QtWidgets.QLineEdit(self.centralwidget)
        self.query_bar.setObjectName("query_bar")
        self.verticalLayout_2.addWidget(self.query_bar)
        self.splitter_2 = QtWidgets.QSplitter(self.centralwidget)
        self.splitter_2.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_2.setObjectName("splitter_2")
        self.image_view_holder = QtWidgets.QGroupBox(self.splitter_2)
        self.image_view_holder.setObjectName("image_view_holder")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.image_view_holder)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.image_tree_view = QtWidgets.QTreeView(self.image_view_holder)
        self.image_tree_view.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.image_tree_view.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.image_tree_view.setObjectName("image_tree_view")
        self.verticalLayout_4.addWidget(self.image_tree_view)
        self.tag_tree_holder = QtWidgets.QGroupBox(self.splitter_2)
        self.tag_tree_holder.setObjectName("tag_tree_holder")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.tag_tree_holder)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.tag_tree_view = QtWidgets.QTreeView(self.tag_tree_holder)
        self.tag_tree_view.setObjectName("tag_tree_view")
        self.verticalLayout_3.addWidget(self.tag_tree_view)
        self.splitter = QtWidgets.QSplitter(self.splitter_2)
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName("splitter")
        self.layoutWidget = QtWidgets.QWidget(self.splitter)
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.current_tags_list = QtWidgets.QListWidget(self.layoutWidget)
        self.current_tags_list.setObjectName("current_tags_list")
        self.verticalLayout.addWidget(self.current_tags_list)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.rating_box = QtWidgets.QSpinBox(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rating_box.sizePolicy().hasHeightForWidth())
        self.rating_box.setSizePolicy(sizePolicy)
        self.rating_box.setObjectName("rating_box")
        self.horizontalLayout.addWidget(self.rating_box)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.media_label = MediaLabel(self.splitter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.media_label.sizePolicy().hasHeightForWidth())
        self.media_label.setSizePolicy(sizePolicy)
        self.media_label.setMinimumSize(QtCore.QSize(100, 100))
        self.media_label.setBaseSize(QtCore.QSize(0, 0))
        self.media_label.setObjectName("media_label")
        self.verticalLayout_2.addWidget(self.splitter_2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1622, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuEdit = QtWidgets.QMenu(self.menubar)
        self.menuEdit.setObjectName("menuEdit")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionClose = QtWidgets.QAction(MainWindow)
        self.actionClose.setObjectName("actionClose")
        self.action_new_tag = QtWidgets.QAction(MainWindow)
        self.action_new_tag.setObjectName("action_new_tag")
        self.action_walk_roots = QtWidgets.QAction(MainWindow)
        self.action_walk_roots.setObjectName("action_walk_roots")
        self.action_manage_roots = QtWidgets.QAction(MainWindow)
        self.action_manage_roots.setObjectName("action_manage_roots")
        self.menuFile.addAction(self.actionClose)
        self.menuEdit.addAction(self.action_new_tag)
        self.menuEdit.addAction(self.action_walk_roots)
        self.menuEdit.addAction(self.action_manage_roots)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Photag"))
        self.image_view_holder.setTitle(_translate("MainWindow", "Images"))
        self.tag_tree_holder.setTitle(_translate("MainWindow", "Tag Tree"))
        self.label_2.setText(_translate("MainWindow", "Rating"))
        self.media_label.setText(_translate("MainWindow", "Image"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuEdit.setTitle(_translate("MainWindow", "Edit"))
        self.actionClose.setText(_translate("MainWindow", "Close"))
        self.action_new_tag.setText(_translate("MainWindow", "New Tag"))
        self.action_new_tag.setShortcut(_translate("MainWindow", "Ctrl+Shift+T"))
        self.action_walk_roots.setText(_translate("MainWindow", "Update All Roots"))
        self.action_manage_roots.setText(_translate("MainWindow", "Manage Roots"))

from MediaLabel import MediaLabel
